import type { MetadataRoute } from "next";

const SITE = "https://positivecheck.com";

type Priority = 0.3 | 0.7 | 0.8 | 0.9 | 1.0;
type Freq = "weekly" | "monthly" | "yearly";

interface Entry {
  path: string;
  lastmod: string;
  changefreq: Freq;
  priority: Priority;
  images?: string[];
}

const entries: Entry[] = [
  { path: "/", lastmod: "2026-04-19", changefreq: "weekly", priority: 1.0,
    images: ["/images/senior-talking-on-the-phone1.webp", "/images/lola-from-positive-check.webp", "/images/wellness-dash-2.png"] },
  { path: "/about", lastmod: "2026-04-22", changefreq: "monthly", priority: 0.8,
    images: ["/images/family-gathering-dinner.png"] },
  { path: "/about/clinical-standards", lastmod: "2026-04-22", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/how-it-works", lastmod: "2026-02-06", changefreq: "monthly", priority: 0.9,
    images: ["/images/senior-talking-on-the-phone1.webp"] },
  { path: "/platform", lastmod: "2026-02-13", changefreq: "monthly", priority: 0.9,
    images: ["/images/admin-console-dashboard-new.png", "/images/wellness-dash-2.png"] },
  { path: "/roi-calculator", lastmod: "2026-02-22", changefreq: "monthly", priority: 0.9,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/contact", lastmod: "2026-02-06", changefreq: "monthly", priority: 0.7,
    images: ["/images/healthcare-care-coordinator.png"] },
  { path: "/blog", lastmod: "2025-07-05", changefreq: "weekly", priority: 0.8 },
  { path: "/blog/ai-companions-for-senior-loneliness-and-caregiver-stress", lastmod: "2025-07-05", changefreq: "monthly", priority: 0.7,
    images: ["/images/ai-companion-senior-wellness.png"] },
  { path: "/blog/senior-sleep-health-fall-prevention-wellness-monitoring", lastmod: "2025-06-27", changefreq: "monthly", priority: 0.7,
    images: ["/images/senior-sleep-safety-bedroom.png"] },
  { path: "/blog/importance-of-checking-in-care-communities", lastmod: "2025-03-17", changefreq: "monthly", priority: 0.7,
    images: ["/images/senior-care-family-visit.png"] },
  { path: "/blog/maintaining-social-connections", lastmod: "2025-03-10", changefreq: "monthly", priority: 0.7,
    images: ["/images/senior-social-connections.png"] },
  { path: "/blog/senior-phone-check-ins-mental-health-safety-benefits", lastmod: "2025-01-25", changefreq: "monthly", priority: 0.7,
    images: ["/images/senior-phone-check-in.png"] },
  { path: "/blog/role-of-technology-in-senior-care", lastmod: "2025-01-25", changefreq: "monthly", priority: 0.7,
    images: ["/images/senior-technology-care.png"] },
  { path: "/privacy", lastmod: "2026-03-18", changefreq: "yearly", priority: 0.3 },
  { path: "/terms", lastmod: "2026-03-18", changefreq: "yearly", priority: 0.3 },
  { path: "/case-studies/scaling-patient-engagement", lastmod: "2026-02-22", changefreq: "monthly", priority: 0.8,
    images: ["/images/healthcare-care-coordinator.png"] },
  { path: "/solutions", lastmod: "2026-04-14", changefreq: "monthly", priority: 0.9,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/faq", lastmod: "2026-04-14", changefreq: "monthly", priority: 0.7,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/remote-patient-monitoring", lastmod: "2026-02-24", changefreq: "monthly", priority: 0.9,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/remote-patient-monitoring/faq", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/remote-patient-monitoring/cpt-99457-billing-guide", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/remote-patient-monitoring/interactive-communication-requirement", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/remote-patient-monitoring/patient-selection", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/remote-patient-monitoring/vs-device-only-monitoring", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/chronic-care-management", lastmod: "2026-02-24", changefreq: "monthly", priority: 0.9,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/chronic-care-management/faq", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/chronic-care-management/cpt-99490-billing-guide", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/chronic-care-management/2-chronic-conditions-requirement", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/chronic-care-management/20-minutes-monthly-requirement", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/chronic-care-management/vs-in-house-care-coordinators", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/post-discharge-follow-up", lastmod: "2026-02-24", changefreq: "monthly", priority: 0.9,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/post-discharge-follow-up/faq", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/post-discharge-follow-up/cpt-99495-billing-guide", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/post-discharge-follow-up/30-day-readmission-reduction", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/post-discharge-follow-up/post-discharge-contact-timing", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/solutions/post-discharge-follow-up/vs-manual-discharge-outreach", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8,
    images: ["/images/admin-console-dashboard-new.png"] },
  { path: "/resources", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8 },
  { path: "/resources/glossary", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8 },
  { path: "/resources/glossary/cpt-99495", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/cpt-99496", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/transitional-care-management", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/30-day-readmission", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/care-coordination", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/cpt-99453", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/cpt-99454", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/cpt-99457", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/cpt-99458", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/remote-patient-monitoring", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/cpt-99490", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/cpt-99439", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/cpt-99487", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/cpt-99489", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/chronic-care-management", lastmod: "2026-04-20", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/hipaa-compliance", lastmod: "2026-04-21", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/business-associate-agreement", lastmod: "2026-04-21", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/ephi", lastmod: "2026-04-21", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/hitech-act", lastmod: "2026-04-21", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/principal-care-management", lastmod: "2026-04-21", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/annual-wellness-visit", lastmod: "2026-04-21", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/interactive-communication-requirement", lastmod: "2026-04-21", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/glossary/patient-engagement", lastmod: "2026-04-21", changefreq: "monthly", priority: 0.7 },
  { path: "/resources/compare", lastmod: "2026-04-19", changefreq: "monthly", priority: 0.8 },
  { path: "/resources/billing-guide", lastmod: "2026-04-21", changefreq: "monthly", priority: 0.9 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  return entries.map((e) => ({
    url: `${SITE}${e.path}`,
    lastModified: new Date(e.lastmod),
    changeFrequency: e.changefreq,
    priority: e.priority,
    ...(e.images?.length
      ? { images: e.images.map((img) => `${SITE}${img}`) }
      : {}),
  }));
}
